# 指定该工作流的名字
name: Cppcheck action
# 定义触发该工作流的事件，这里是当有 push 到 main 分支时触发
on:
  push:
  pull_request:
# 定义工作流的作业，这里只有一个作业，名字为 cppcheck
jobs:
  cppcheck:
    # 指定运行该作业的环境，这里使用最新版本的 Ubuntu
    runs-on: ubuntu-latest
    # 定义作业的步骤
    steps:
      # 第一步：检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v2
      # 第二步：安装 Cppcheck 工具
      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck
      # 第三步：运行 Cppcheck 进行代码静态分析
      #        
      - name: Run Cppcheck
      # --enable 指定使能的检查类型
      # --language 指定代码语言为 C
      # --platform 指定目标平台为 unix32
      # --std 指定代码标准为 C99
      # --force 强制检查所有文件
      # -i 用于排除不需要检查的目录 i为ignore的意思
        run: cppcheck --enable=warning,portability,performance \
                      --language=c \
                      --platform=unix32 \
                      --std=c99 \
                      --force . \
                      -i ./UnityTesting/ \
                      -i ./os/
